# Premium SSD StorageClass (for production)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: premium-retain
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Premium_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
# Standard HDD StorageClass (for development/testing)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-delete
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
